name: Time_Series_L2D
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - contourpy=1.3.3
  - cycler=0.11.0
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libiconv=1.16
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - ncurses=6.5
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tornado=6.5.1
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - comm==0.2.3
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - ipympl==0.9.8
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyterlab-widgets==3.0.16
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.6
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyyaml==6.0.3
      - stack-data==0.6.3
      - sympy==1.14.0
      - torch==2.9.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
prefix: /opt/anaconda3/envs/Time_Series_L2D
