name: Time_Series_L2D
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - contourpy=1.3.3=py311h20e30b6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py311h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.9=py311haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libtiff=4.7.1=h367c460_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.6=py311hca03da5_1
  - matplotlib-base=3.10.6=py311h37b8ce2_1
  - ncurses=6.5=hee39554_0
  - numpy=2.3.5=py311h4bb6f22_0
  - numpy-base=2.3.5=py311h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py311hca03da5_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pyparsing=3.2.5=py311hca03da5_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - asttokens==3.0.1
      - comm==0.2.3
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - ipympl==0.9.8
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyterlab-widgets==3.0.16
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.6
      - parso==0.8.5
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyyaml==6.0.3
      - stack-data==0.6.3
      - sympy==1.14.0
      - torch==2.9.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
prefix: /opt/anaconda3/envs/Time_Series_L2D
